### ISSUE TITLE
Dark Theme: User card colors are still in light mode

### ISSUE THREAD

**Issue by gioele97** [pat-s/gitea-github-theme#3]
Hi,
like shown in the image below the card shown in the profile of the user is still white, thus the text results a bit hard to read

![image](https://user-images.githubusercontent.com/6464661/137500545-24711e65-a927-4379-bbf9-8dd7435ea08e.png)

Edit: The version of gitea used is 1.15.4

**Comment by pat-s** [comment]
Thanks, I'll fix it in the next days.

**Comment by pat-s** [comment]
Don't forget to clear the cache after using the latest version of the theme.

**Comment by gioele97** [comment]
Thanks for the reminder.
I lost track how many times i've been saying it at work too :)
