### ISSUE TITLE
Auto-switching colours

### ISSUE THREAD

**Issue by gvandewiel86** [pat-s/gitea-github-theme#5]
Hi Patrick,

i am using your github repo to post this as i don't have an codeberg account.

The perform the auto-switching based on the light-mode or dark-mode of the OS one could use the following CSS as discussed in this post [https://blog.jim-nielsen.com/2019/conditional-syntax-highlighting-in-dark-mode-with-css-imports/](https://blog.jim-nielsen.com/2019/conditional-syntax-highlighting-in-dark-mode-with-css-imports/).

```css
@import url("theme-github-light.css") screen and (prefers-color-scheme: light);
@import url("theme-github-dark.css") screen and (prefers-color-scheme: dark);
```

I renamed the normal `theme-github.css` to `theme-github-light.css`.

**Comment by pat-s** [comment]
You can sign-in with GH on Codeberg as well.

> The perform the auto-switching based on the light-mode or dark-mode of the OS one could use the following CSS as discussed in this post [blog.jim-nielsen.com/2019/conditional-syntax-highlighting-in-dark-mode-with-css-imports](https://blog.jim-nielsen.com/2019/conditional-syntax-highlighting-in-dark-mode-with-css-imports/).

This already works.
If you use the `theme-github-auto`, Gitea honors your file system preferences and the auto-switch works.
